module.exports = [
  "Go grab a glass of water.",
  "Slowly look all the way left, then right.",
  "Slowly look all the way up, then down.",
  "Close your eyes and take few deep breaths.",
  "Close your eyes and relax.",
  "Stretch your legs.",
  "Stretch your arms.",
  "Is your sitting posture correct?",
  "Slowly turn head to side and hold for 10 seconds.",
  "Slowly tilt head to side and hold for 5-10 seconds.",
  "Stand from your chair and stretch.",
  "Refocus your eyes on an object at least 20 meters away.",
  "Take a moment to think about something you appreciate.",
  "Take a moment to smile at being alive.",
  "A truly ergonomic workstation is one that you regularly push away from.",
  "Close your eyes and count your breaths.",
  "Close your eyes and name the things you hear.",
  // "Place your fingertips on your shoulders. Roll your shoulders forward for 10 seconds, then backward.",
  // "Raise your right arm, stretch it over your head to the left, and hold for 10 seconds. Repeat on the other side.",
  // "With your right hand, grab each finger of your left hand in turn and squeeze. Repeat on the other side.",
  // "Stand up and do a lunge. Hold for 10 seconds, then do the other leg.",
  // "Close your eyes and simply notice whatever arises in current moment, without judgement.",
  // "One should focus every 20 minutes for 20 seconds on an object that is 20 feet distance.",
  "If you need help, ask for it.",
  "Do one thing at a time.",
];
